# -*- coding: utf-8 -*-
"""automl.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BvpH-prqqf-eTV5WtNERTY_mSie29Ixd
"""

rptupip install h2o

!nvidia-smi

!apt-get install default-jre
!java -version

!pip install h2o

import h2o

h2o.init()

from h2o.automl import H2OAutoML

df = h2o.import_file('/content/drive/MyDrive/IIIT-K Intern/country_wise_latest.csv')

df.types

df.describe()

df_train,df_test,df_valid = df.split_frame(ratios=[.7, .15])

df_train

y = "WHO Region"
x = df.columns
x.remove(y)
x.remove("Country/Region")

aml = H2OAutoML(max_models = 10, seed = 10, exclude_algos = ["StackedEnsemble", "DeepLearning"], verbosity="info", nfolds=0)

aml.train(x = x, y = y, training_frame = df_train, validation_frame=df_valid)

lb = aml.leaderboard

lb.head()

df_pred=aml.leader.predict(df_test)

df_pred.head()

aml.leader.model_performance(df_test)

model_ids = list(aml.leaderboard['model_id'].as_data_frame().iloc[:,0])

model_ids

h2o.get_model([mid for mid in model_ids if "XGBoost" in mid][0])

out = h2o.get_model([mid for mid in model_ids if "XGBoost" in mid][0])

out.params

out.convert_H2OXGBoostParams_2_XGBoostParams()

out

out_gbm = h2o.get_model([mid for mid in model_ids if "GBM" in mid][0])

out.confusion_matrix()

out.varimp_plot()

